#!/usr/bin/env bash

function bootstrap {
  local shome="${_homebrew_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      ruby "$shome/script/brew_install" "$shome/install"
      brew update
      ;;
  esac
}

bootstrap
