#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin)
      true
      ;;
    *)
      return 0
      ;;
  esac

  if ! type -P brew >/dev/null; then
    return 1
  fi

  return 0
}

source sub "$0" "$@"

