#!/usr/bin/env bash

function _homebrew_profile {
  local shome="${_homebrew_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/install/sbin:$shome/install/bin:$PATH"

  export HOMEBREW_PREFIX="$HOME/homebrew"
}

_homebrew_profile
