#!/usr/bin/env bash

function profile {
  local shome="${_homebrew_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/install/sbin:$shome/install/bin:$PATH"
}

profile
